title: Aayush Munshi

description:
Data Analyst Intern
MS in Applied Mathematics | BS in Mathematical Finance |
Snowflake | dbt | SQL | Tableau | 
aayushmunshi10@gmail.com
<a href="https://www.linkedin.com/in/aayush-munshi-991370222/">Linkedin</a> |




theme: jekyll-theme-Architect
